
// This file has been generated by the GUI designer. Do not modify.
namespace PGestion
{
	public partial class BotonAdd
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label Introducir;
		private global::Gtk.Entry entry1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button botonAceptar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGestion.BotonAdd
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "PGestion.BotonAdd";
			this.Title = global::Mono.Unix.Catalog.GetString ("BotonAdd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PGestion.BotonAdd.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.Introducir = new global::Gtk.Label ();
			this.Introducir.Name = "Introducir";
			this.Introducir.LabelProp = global::Mono.Unix.Catalog.GetString ("Introduce un valor para añadir");
			this.vbox1.Add (this.Introducir);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Introducir]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.vbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			this.botonAceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.vbox2.Add (this.botonAceptar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.botonAceptar]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w5.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 311;
			this.Show ();
		}
	}
}
