
// This file has been generated by the GUI designer. Do not modify.
namespace PGestion
{
	public partial class CategoriaView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGestion.CategoriaView
			this.Name = "PGestion.CategoriaView";
			this.Title = global::Mono.Unix.Catalog.GetString ("CategoriaView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
